defaults: &defaults
  adapter: mysql2
  host: localhost
  encoding: utf8

development:
  database: my5_developments
  <<: *defaults

test: &test
  database: my5_test
  <<: *defaults

staging:
  database: staging
  <<: *defaults

production:
  adapter: mysql2
  database: my5_developments
  host: localhost

