defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: 
  encoding: utf8
  socket: /tmp/mysql.sock

development:
  database: my5_development
  <<: *defaults

test: &test
  database: my5_test
  <<: *defaults

staging: &mysql
  adapter: mysql
  encoding: utf8
  socket: /tmp/mysql.sock
  username: admin
  password: password
  database: staging
production:
  adapter: mysql2
#  host: 127.0.0.1
  socket: /tmp/mysql.sock
  database: my5admin_my5
  pool: 5
  timeout: 5000
  username: my5admin_my5
  password: foster$woke+blow
